import Head from 'next/head';
import { Button, Card, Container, Grid, Link, Spacer, Text, Image } from '@nextui-org/react';
import { Carousel, Category, Header } from '../components';

function Home() {
  const itemBanners = [
    {
      id: 0,
      image: "banner_2.png",
      title: "image-banner-0"
    },
    {
      id: 1,
      image: "banner_3.png",
      title: "image-banner-1"
    },
    {
      id: 2,
      image: "banner_4.png",
      title: "image-banner-2"
    }
  ];

  const itemServices = [
    {
      id: 0,
      image: "service_1.png",
      name: "Manfaat",
      description: "Memberikan kemanfaatan bagi pembangunan ekonomi, sosial, lingkungan, hukum dan tata kelola bagi perusahaan."
    },
    {
      id: 1,
      image: "service_2.png",
      name: "Kontribusi",
      description: "Berkontribusi meningkatkan nilai tambah dengan prinsip yang terintegrasi, terarah dan terukur dampaknya serta akuntabel."
    },
    {
      id: 2,
      image: "service_3.png",
      name: "Pembinaan",
      description: "Membina usaha mikro dan usaha kecil agar lebih tangguh dan mandiri serta masyarakat sekitar perusahaan."
    }
  ]

  const itemCategories = [
    {
      id: 0,
      image: "https://res.cloudinary.com/borneos-co/image/upload/v1644567865/images/categories/Semua_eiizmq.svg",
      name: "Semua",
      description: "Semua Kategori"
    },
    {
      id: 1,
      image: "https://res.cloudinary.com/borneos-co/image/upload/v1650784158/images/categories/xfx103dzxgsmhklumm5k.png",
      name: "Pertanian",
      description: "Kategori Pertanian"
    },
    {
      id: 2,
      image: "https://res.cloudinary.com/borneos-co/image/upload/v1650784098/images/categories/pfh9klzrjkut442o24ae.png",
      name: "Fashion",
      description: "Kategori Fashion & Kain"
    },
    {
      id: 3,
      image: "https://res.cloudinary.com/borneos-co/image/upload/v1650784487/images/categories/jrgbaz2nm2cgrxyufwjt.png",
      name: "Perdagangan",
      description: "Kategori Perdagangan"
    }
  ];

  return (
    <div>
      <Head>
        <title>UMKADEMI</title>
        <meta name="description" content="TJSL Mitra Merchant - Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container xl css={{ d: 'flex', fontFamily: '$sans', w: '100%'}}>
          <Header />
          <Spacer y={1} />
          <Carousel items={itemBanners} />
          <Container md css={{ marginTop: '1em' }}>
            <Grid.Container gap={1} justify="start" alignItems="center" css={{}}>
              {itemServices && itemServices.length && itemServices.map(item => 
                <Grid key={item.id} xs={4} css={{ height: "100%"}}>
                  <Card isPressable isHoverable variant="bordered" css={{ p: "$4", "&:hover" : { borderColor: "$blue400", borderWidth: "2px"} }}>
                    <Grid.Container css={{ overflow: "hidden"}}>
                      <Grid key={item.id} xs={3}>
                        <Image
                          alt={item.name || ''}
                          src={item.image || ''}
                        />
                      </Grid>
                      <Grid key={item.id} xs={9}>
                        <Card variant="flat" css={{ background: '#fff', p: "$0", ml: "$4", borderRadius: "$0" }}>
                          <Text color="$gray800" h4 css={{ lineHeight: "$xs", mb: 5}}>{item.name || ''}</Text>
                          <Text color="$gray700" size={14}>{item.description || ''}</Text>
                        </Card>
                      </Grid>
                    </Grid.Container>
                  </Card>
                </Grid>
              )}
            </Grid.Container>
          </Container>
          <Container md css={{ marginTop: '.5em', paddingBottom: '1em'}}>
            <Text 
              h1
              size={18}
              css={{
                display: "block",
                flex: "1",
                textGradient: "45deg, $blue600 -20%, $yellow600 30%",
                marginTop: "1em",
                marginLeft: "5px"
              }}
              weight="bold"
            >Kategori Mitra Binaan TJSL PT. Pupuk Kaltim</Text>
            <Grid.Container gap={1} justify="start" alignItems="center" css={{marginTop: "5px"}}>
              {itemCategories && itemCategories.length && itemCategories.map(item => 
                <Grid key={item.id} xs={2} css={{ m: '0'}}>
                  <Category item={item} />
                </Grid>
              ) || null}
            </Grid.Container>
          </Container>
          
          
          <Grid.Container gap={2} justify="center" alignItems="center">
            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"

                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>
            
            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"

                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>

            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"

                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>

            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"

                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>

            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"

                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>
          </Grid.Container>
        </Container>
      </main>
      <footer></footer>
    </div>
  )
}

export default Home;
