import Head from 'next/head';
// import { Button, Card, Container, Grid, Link, Spacer, Text, Image } from '@nextui-org/react';
import {
  Box,
  Button,
  Card,
  Container,
  Flex,
  Image,
  Text,
} from '@chakra-ui/react';
import { Carousel, Category, Header } from '../components';
import PropTypes from 'prop-types';
import HomePageContainer from '../page_container/home/HomePageContainer';
import Footer from '../components/Footer';

function Home(props) {
  const { isMobile } = props;

  return (
    <div>
      <Head>
        <title>BRAND TJSL</title>
        <meta
          name="description"
          content="TJSL Mitra Merchant - Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box minHeight="100vh">
          <HomePageContainer {...props} />
          {/* <Container md css={{ marginTop: "1em" }}>
            <Grid.Container gap={4} justify="start" alignItems="center" css={{}}>
              {itemServices && itemServices.length && itemServices.map(item => 
                <Grid key={item.id} xs={4} css={{ height: "320px"}}>
                  <Card isPressable isHoverable variant="bordered" css={{ p: "$4", "&:hover" : { borderColor: "$blue400", borderWidth: "2px"} }}>
                    <Grid.Container css={{ overflow: "hidden"}}>
                      <Grid key={item.id} xs={3}>
                        <Image
                          alt={item.name || ''}
                          src={item.image || ''}
                        />
                      </Grid>
                      <Grid key={item.id} xs={9}>
                        <Card variant="flat" css={{ background: '#fff', p: "$0", ml: "$4", borderRadius: "$0" }}>
                          <Text color="$gray800" h4 css={{ lineHeight: "$xs", mb: 5}}>{item.name || ''}</Text>
                          <Text color="$gray700" size={14}>{item.description || ''}</Text>
                        </Card>
                      </Grid>
                    </Grid.Container>
                  </Card>
                </Grid>
              )}
            </Grid.Container>
          </Container> */}
          {/* <Grid.Container css={{marginTop: "1em", marginBottom: "1em"}} gap={2} alignItems="center">
            <Grid xs={6}>
              <div>
                <Text
                  h1
                  size={40}
                  css={{
                    textGradient: "45deg, $blue600 -20%, $blue800 50%",
                  }}
                  weight="bold"
                >Pupuk Kaltim</Text>
                <Text
                  h1
                  size={60}
                  css={{
                    textGradient: "45deg, $yellow600 -20%, $red600 100%",
                    lineHeight: "55px"
                  }}
                  weight="bold"
                >UMKM AKADEMI</Text>
                <Text size="1.25em" weight="normal" css={{ marginTop: 20}}>Adalah program persembahan TJSL Pupuk Kaltim sebagai bentuk kontribusi nyata terhadap pertumbuhan dan kemajuan UMKM di seluruh Indonesia, khususnya Kalimantan Timur dengan berkolaborasi bersama para profesional dan pemangku kepentingan</Text>
                <Text size="1em" weight="bold" color="gray" css={{ marginTop: 20}}>Didukung Oleh:</Text>
                <div style={{ marginLeft: '4em'}}>
                  <Image containerCss={{ margin: 0}} alt="logo-pkt" src="/pkt-color.png" width={180} />
                </div>
              </div> 
            </Grid> */}
          {/* <Grid xs={6}>
              <Image 
                alt="home-thumbnail"
                src="/home.png"
                width={460}
                objectFit="cover"
              />
            </Grid>
          </Grid.Container>
        </Container> */}

          {/* <div style={{ background: "#f0f8ff", padding: "2em" }}>
          <Container md>
            <Text
              css={{ marginLeft: "12px" }}
              color="#2667a2"
              weight="bold"
              size="1.25em"
            >
              Nilai-Nilai [BRAND TJSL]
            </Text>
            <Grid.Container gap={2}>
              <Grid xs={4}>
                <Card css={{ p: "2em", textAlign: "center"}}>
                  <Text h4>Mau Maju dan Berkontribusi</Text>
                </Card>
              </Grid>
              <Grid xs={4}>
                <Card css={{ p: "2em", textAlign: "center" }}>
                  <Text h4>Integritas Tinggi</Text>
                </Card>
              </Grid>
              <Grid xs={4}>
                <Card css={{ p: "2em", textAlign: "center" }}>
                  <Text h4>Bersama Meraih Sukses</Text>
                </Card>
              </Grid>
            </Grid.Container>
          </Container>
        </div> */}

          {/* <Container
          xl
          css={{ d: "flex", fontFamily: "$sans", w: "100%", mb: "2em" }}
        >
          <Container md css={{ marginTop: ".5em", paddingBottom: "1em" }}>
            <Text
              h1
              size={18}
              css={{
                display: "block",
                flex: "1",
                textGradient: "45deg, $blue600 -20%, $yellow600 30%",
                marginTop: "1em",
                marginLeft: "5px",
              }}
              weight="bold"
            >
              Kategori Mitra Binaan TJSL PT. Pupuk Kaltim
            </Text>
            <Grid.Container gap={1} justify="start" alignItems="center" css={{marginTop: "5px"}}>
              {itemCategories && itemCategories.length && itemCategories.map(item => 
                <Grid key={item.id} xs={2} css={{ m: '0'}}>
                  <Category item={item} />
                </Grid>
              ) || null}
            </Grid.Container>
          </Container> */}

          {/* <Grid.Container gap={2} alignItems="center">
            <Grid>
              <Card css={{ p: "$6", mw: "400px" }} isPressable isHoverable>
                <Card.Header>
                  <Image
                    alt="nextui logo"
                    src="https://avatars.githubusercontent.com/u/86160567?s=200&v=4"
                    width="34px"
                    height="34px"
                  />
                  <Grid.Container css={{ pl: "$6" }}>
                    <Grid xs={12}>
                      <Text h4 css={{ lineHeight: "$xs" }}>
                        Warung Bucu
                      </Text>
                    </Grid>
                    <Grid xs={12}>
                      <Text css={{ color: "$accents8" }}>Makanan & minuman</Text>
                    </Grid>
                  </Grid.Container>
                </Card.Header>
                <Card.Body css={{ py: "$2" }}>
                  <Text>
                    Mitra binaan TJSL PT. Pupuk Kaltim yang telah berdiri sejak 2016
                  </Text>
                </Card.Body>
                <Card.Footer>
                  <Link
                    icon
                    color="primary"
                    target="_blank"
                    href="https://borneos.co"
                  >
                    Katalog Online
                  </Link>
                </Card.Footer>
              </Card>
            </Grid>
            
          </Grid.Container> */}
        </Box>
      </main>
      {/* <footer style={{ background: "#135690", padding: "1em" }}>
        <Container xl>
          <Text weight="semibold" color="#fff">
            [BRAND TJSL] &copy; 2022 All Right Reserved
          </Text>
        </Container>
      </footer> */}
    </div>
  );
}

Home.propTypes = {
  isMobile: PropTypes.bool,
};

export default Home;
